name: Build and Deploy Documentation

on: [push, pull_request]

jobs:
  documentation:
    runs-on: ubuntu-22.04

    env:
      FC: gfortran
      GCC_V: 12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies Ubuntu
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V} python3-dev graphviz
        sudo pip install ford markdown==3.3.4

    - name: Build Developer Documenation
      run: |
        ford doc/ford-front-matter.md

    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: doc/ford_site
        if-no-files-found: error

    - name: Broken Link Check
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: technote-space/broken-link-checker-action@v1
      with:
        TARGET: file://${{ github.workspace }}/ford_site/index.html
        RECURSIVE: true
        ASSIGNEES: ${{ github.actor }}

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages
        folder: doc/ford_site